#!/usr/bin/env node
// Overall Process:
// 1. Search spotify for album data
// 2. Sort albums by natural string similarity
// 4. Make a request to save the album in spotify

var readline = require('readline');
var fs = require('fs');

var unirest = require('unirest');
var natural = require('natural');
var Q = require('q');
var R = require('ramda');
var sleep = require('sleep');


var main = function() {
	readUserInput().then(function(config) {
		var saveAlbumsToSpotifyWithConfig = R.partial(saveAlbumsToSpotify, [config]);
		var getSpotifyAlbumsWithConfig = R.partial(getSpotifyAlbums, [config]);

		getRdioAlbums(config)
			.then(getSpotifyAlbumsWithConfig)
			.then(saveAlbumsToSpotifyWithConfig);
	});
}


var readUserInput = function() {
	var dfd = Q.defer();
	config = {};

	var rl = readline.createInterface({
		input: process.stdin,
		output: process.stdout
	});

	rl.question('Path to Rdio album data: ', function(answer) {
		config.albumFilePath = answer;
		rl.question('Access key: ', function(answer) {
			config.accessToken = answer;
			rl.close();
			dfd.resolve(config);
		});
	});

	return dfd.promise;
};


var getRdioAlbums = function(config) {
	// Each album is:
	// {album: <album name>, artist: <artist name>}
	var albums = [];
	var fileContents = new String(fs.readFileSync(config.albumFilePath));

	fileContents.split('\n').forEach(function(albumData, idx) {
		if (!albumData) {
			return;
		}
		try {
			var rdioAlbumData = JSON.parse(albumData);
			var albumObject = {
				name: rdioAlbumData.name,
				artist: rdioAlbumData.artist
			};
			var upc = null;
			if (rdioAlbumData.upcs && rdioAlbumData.upcs.length) {
				upc = rdioAlbumData.upcs[0];
			}
			albums.push({
				name: rdioAlbumData.name,
				artist: rdioAlbumData.artist,
				upc: upc
			});
		} catch (e) {
			console.error('Error while parsing album JSON', e);
		}
	});

	var dfd = Q.defer();
	dfd.resolve(albums);
	return dfd.promise;
};

var getSpotifyAlbums = function(config, rdioAlbums) {
	console.log('Fetching ' + rdioAlbums.length + ' Rdio albums to import to Spotify');

	var spotifyAlbumIds = [];
	var dfd = Q.defer();

	if (!rdioAlbums.length) {
		dfd.resolve([]);
	} else {
		var firstAlbum = rdioAlbums.pop();
		getNextAlbum(config, firstAlbum, spotifyAlbumIds, dfd, rdioAlbums);
	}

	return dfd.promise;
};

var getNextAlbum = function(config, album, spotifyAlbumsResult, dfd, allAlbums) {
	var query = 'album:' + album.name + ' artist:' + album.artist;
	if (album.upc) {
		query = 'upc:' + album.upc;
	}
	console.log('Fetching album: ' + album.name);
	var request = unirest
		.get('https://api.spotify.com/v1/search')
		.type('json')
		.headers({
			'Authorization': 'Bearer ' + config.accessToken
		})
		.query({
			q: query,
			type: 'album',
			limit: '5'
		})
		.end(function(response) {
			if (!response.body.albums || response.body.albums.total == 0) {
				if (response.headers['retry-after'] && response.code == 429) {
					sleep.sleep(response.headers['retry-after']);
					getNextAlbum(config, album, spotifyAlbumsResult, dfd, allAlbums);
					return;
				}
				var errorMessage = 'Error while retrieving: ' + album.name;
				if (response.body.message || response.code != 200) {
					errorMessage += '. Message: ' + response.body.message;
					errorMessage += ". " + response.code;
					console.error(errorMessage);
				} else if (response.body.albums.total == 0) {
					console.error('No matches found for album: ' + album.name);
				}
				if (!allAlbums.length) {
					dfd.resolve(spotifyAlbumsResult);
					return;
				} else {
					var nextAlbum = allAlbums.pop();
					getNextAlbum(config, nextAlbum, spotifyAlbumsResult, dfd, allAlbums);
					return;
				}
			}

			var albums = R.sortBy(
				R.compose(
					R.partial(natural.JaroWinklerDistance, [album.name.toLowerCase()]),
					R.toLower,
					R.prop('name')
				)
			)(response.body.albums.items);
			spotifyAlbumsResult.push(albums[0].id);
			if (!allAlbums.length) {
				dfd.resolve(spotifyAlbumsResult);
			} else {
				var nextAlbum = allAlbums.pop();
				getNextAlbum(config, nextAlbum, spotifyAlbumsResult, dfd, allAlbums);
			}
		});
};

/**
 * We can only save 50 albums per call - so they need to be batched
 */
var saveAlbumsToSpotify = function(config, spotifyAlbumIds) {
	console.log('saveAlbumsToSpotify! ' + spotifyAlbumIds.length);
	var batches = R.splitEvery(50, spotifyAlbumIds);
	batches.forEach(R.partial(saveAlbumBatch, [config]));
};

var saveAlbumBatch = function(config, spotifyAlbumIds) {
	console.log('Saving album batch of 50...');
	var requestData = spotifyAlbumIds
			.map(function(albumId) {return '"' + albumId + '"';})
			.join(',');
	requestData = '[' + requestData + ']';

	var nextRequest = unirest
		.put('https://api.spotify.com/v1/me/albums')
		.type('json')
		.headers({
			'Authorization': 'Bearer ' + config.accessToken
		})
		.send(requestData)
		.end(function(response) {
			if (!response.code == 201 || !response.code == 200) {
				console.error('Error while saving album batch: "' + response.body.message + '"');
			}
		});
};

main();
